In [186]:
%matplotlib inline

If you haven't installed PyTorch yet, follow the instructions on the [PyTorch Get Started page](https://pytorch.org/get-started/locally/) to pick the right install command for your system.

<div class="alert alert-info"><h4>Further reading:</h4><p>This notebook is adapted from the <a href="https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html">PyTorch: A 60 Minute Blitz</a> tutorial on the PyTorch website. For documentation and more tutorials, visit <a href="https://pytorch.org">pytorch.org</a></p></div>


# PyTorch

PyTorch is a free, open-source machine learning framework with a Python interface that's widely used both in research and industry. For the purposes of this class, it lets us easily set up and train neural network models. These lab notebooks are just a brief introduction to PyTorch, but will hopefully get you comfortable with the terms and tools that will be important, starting with perhaps the most fundamental: tensors

If you haven't installed PyTorch yet, follow the instructions on the [PyTorch Get Started page](https://pytorch.org/get-started/locally/) to pick the right install command for your system.


## Summary

This notebook introduces **tensors**, the core data structure in PyTorch, and the basic operations you'll use throughout the course.

1. **Initializing Tensors** — create tensors directly from Python data, from NumPy arrays, with random/constant values (`torch.rand`, `torch.ones`, `torch.zeros`), or using another tensor as a template.
2. **Tensor Attributes** — inspect a tensor's `shape`, `dtype`, and `device`.
3. **Tensor Operations**
   - 3.1 Element-wise arithmetic (`+`, `-`, `*`, `/`)
   - 3.2 Matrix multiplication with `@`
   - 3.3 NumPy-style indexing and slicing
   - 3.4 In-place operations (the `_` suffix) and why to use them sparingly
   - 3.5 Joining tensors with `torch.cat`
   - 3.6 `torch.stack` vs `torch.cat`
   - 3.7 Moving tensors to a GPU (CUDA / MPS) and comparing speed with the CPU



# Tensors

Tensors are a data structure—a way of storing numbers. They are very similar to arrays, which you may have encountered before (such as the ndarrays in NumPy). A tensor can be as simple as a one-dimensional list of numbers:

$$
\begin{bmatrix} 1 & 2 & 3 \end{bmatrix}
$$

But a tensor can also be a 2-dimensional array of numbers:

$$
\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}
$$

Or it can have 3, 4, or any other number of dimensions. You might talk about a 1x3 tensor (like the first example above) or a 3x3 tensor (like the second example) or an Nx1x32x32 tensor (which we'll see in a later notebook). So, at least as far as the field of machine learning is concerned, a tensor is just a big block of numbers—a multidimensional array.

PyTorch uses tensors to store the data that make up the input to a neural network model (e.g. images for classification), and also uses them to store the parameters that define the model (its weights and biases).

--------------

In [187]:
import torch
import numpy as np

## 1. Initializing Tensors

There are several ways to initialize a tensor—let's look at some examples:

**1.1 Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.

In [188]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, data_tensor.dtype)

tensor([[1, 2],
        [3, 4]]) torch.int64


**1.2 From a NumPy array**

Tensors can be created from NumPy arrays. Note that the new tensor and the NumPy array will share the same memory.

In [189]:
np_array = np.array(data)
data_tensor = torch.from_numpy(np_array)
print(data_tensor)

tensor([[1, 2],
        [3, 4]])


**1.3 With random or constant values**

``shape`` is a tuple of tensor dimensions.



In [190]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1588, 0.2141, 0.3951],
        [0.9357, 0.4553, 0.2122]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**1.4 Using another tensor as a template**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [191]:
data_tensor = torch.tensor([[1, 2], [3, 4]])

print(f"Data Tensor: \n {data_tensor} \n")

x_ones = torch.ones_like(data_tensor) # retains the properties of data_tensor
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(data_tensor, dtype=torch.float) # overrides the datatype of data_tensor
print(f"Random Tensor: \n {x_rand} \n")

Data Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6133, 0.8993],
        [0.5960, 0.0671]]) 



--------------




## 2. Tensor Attributes

Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [ ]:
tensor = torch.rand(3, 4)

print(f"Tensor: \n {tensor} \n")

#Here are 3 common attributes:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
#a device is the piece of hardware whose memory holds the tensor and whose processor runs operations on it.
#Examples:
#cpu — normal system RAM, computed by the CPU
#cuda:0 — the first NVIDIA GPU (cuda:1 would be the second)
#mps — Apple's Metal GPU backend, which is what you'd get on your Mac

Tensor: 
 tensor([[0.2168, 0.0733, 0.3078, 0.7995],
        [0.4876, 0.5630, 0.6815, 0.5640],
        [0.1043, 0.4446, 0.8154, 0.1443]]) 

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




## 3. Tensor Operations

A full list of tensor operations can be found [here](https://pytorch.org/docs/stable/torch.html).

**3.1 Arithmetic (element-wise)**

You can use the usual +, -, \*, / symbols

In [204]:
x = torch.randint(10, (3, 2))
y = torch.randint(10, (3, 2))
print(x, '\n')
print(y, '\n')
z = x + y
print(z, '\n')
w = x * y
print(w, '\n')

tensor([[3, 8],
        [1, 9],
        [3, 9]]) 

tensor([[1, 8],
        [2, 1],
        [9, 4]]) 

tensor([[ 4, 16],
        [ 3, 10],
        [12, 13]]) 

tensor([[ 3, 64],
        [ 2,  9],
        [27, 36]]) 



**3.2 Matrix multiplication**

In [194]:
x = torch.tensor([[0, 1], [-1, 0]])
y = torch.tensor([[4, 0], [0, 4]])
print(x, '\n')
print(y, '\n')
z = x @ y
print(z)

tensor([[ 0,  1],
        [-1,  0]]) 

tensor([[4, 0],
        [0, 4]]) 

tensor([[ 0,  4],
        [-4,  0]])


**3.3 Standard numpy-like indexing and slicing**

In [195]:
tensor = torch.zeros(3, 3)
print(tensor, '\n')
tensor[0, 0] = 3
tensor[:, 2] = 5
print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

tensor([[3., 0., 5.],
        [0., 0., 5.],
        [0., 0., 5.]])


**3.4 In-place operations**

Operations that have a ``_`` suffix are in-place. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.

In [205]:
tensor = torch.zeros(3, 3)
tensor[0, 0] = 3
tensor[:, 2] = 5

print(tensor, "\n")

tensor.add_(20)
print(tensor, "\n")

tensor.sqrt_()
print(tensor, "\n")


tensor([[3., 0., 5.],
        [0., 0., 5.],
        [0., 0., 5.]]) 

tensor([[23., 20., 25.],
        [20., 20., 25.],
        [20., 20., 25.]]) 

tensor([[4.7958, 4.4721, 5.0000],
        [4.4721, 4.4721, 5.0000],
        [4.4721, 4.4721, 5.0000]]) 



<div class="alert alert-info"><h4>Note</h4><p>In-place operations save some memory, but can potentially overwrite values required to compute gradients, so their use is discouraged.</p></div>

**3.5 Joining tensors**

You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension. See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html), another operation that is subtly different from ``torch.cat``.

In [206]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[4.7958, 4.4721, 5.0000, 4.7958, 4.4721, 5.0000],
        [4.4721, 4.4721, 5.0000, 4.4721, 4.4721, 5.0000],
        [4.4721, 4.4721, 5.0000, 4.4721, 4.4721, 5.0000]])


**3.6 `torch.stack` vs `torch.cat`**

Both combine several tensors into one, but they do it differently. `torch.cat` joins tensors along an *existing* dimension, so the output has the same number of dimensions as the inputs. `torch.stack` adds a *new* dimension, so the inputs must all have the exact same shape, and the output has one more dimension than they do.

In [215]:
a = torch.zeros(2, 3)
b = torch.ones(2, 3)

print(f"a: {a}")
print(f"b: {b}", '\n')


a: tensor([[0., 0., 0.],
        [0., 0., 0.]])
b: tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [216]:
# cat: joins along an existing dimension, so the inputs' number of dims is preserved
print(f"cat along dim=0: {torch.cat([a, b], dim=0).shape}")
print(torch.cat([a, b], dim=0), '\n')

print(f"cat along dim=1: {torch.cat([a, b], dim=1).shape}")
print(torch.cat([a, b], dim=1), '\n')

cat along dim=0: torch.Size([4, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

cat along dim=1: torch.Size([2, 6])
tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]]) 



In [217]:
# stack: adds a new dimension, so the inputs must have the exact same shape
print(f"stack along dim=0: {torch.stack([a, b], dim=0).shape}")
print(torch.stack([a, b], dim=0), '\n')

print(f"stack along dim=1: {torch.stack([a, b], dim=1).shape}")
print(torch.stack([a, b], dim=1), '\n')

stack along dim=0: torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

stack along dim=1: torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [1., 1., 1.]]]) 



**3.7 Changing device**

Typically, tensor operations will be faster on a GPU (if supported) than a CPU.

In [199]:
import time

In [200]:
x = torch.rand(8_000, 8_000)
y = torch.rand(8_000, 8_000)
start_time = time.time()

# this should take several seconds to run:
z = x @ y

end_time = time.time()
elapsed_time = end_time - start_time
print(np.round(elapsed_time, 3), " seconds")

0.509  seconds


In [201]:
# move our tensor to the GPU if available

# CUDA: Nvidia GPUs
if torch.cuda.is_available():
    x = x.to('cuda')
    y = y.to('cuda')
    print("CUDA is available. Tensors moved to GPU.")

# MPS: Mac GPUs
if torch.backends.mps.is_available():
    x = x.to('mps')
    y = y.to('mps')
    print("MPS is available. Tensors moved to GPU.")

print(f"Tensor is stored on: {x.device}")

MPS is available. Tensors moved to GPU.
Tensor is stored on: mps:0


In [202]:
# if the tensors were moved to a GPU, this should be faster
z = 0
start_time = time.time()
z = x @ y

end_time = time.time()
elapsed_time = end_time - start_time
print(np.round(elapsed_time, 3), " seconds")

0.0  seconds
